---
  - name: creating users
    hosts: all
    vars_files:
      - vault.yml
      - user_list.yml
    tasks:
      - name: create groups
        ansible.builtin.group:
          name: "{{ item }}"
          state: present
        loop:
          - devops
          - opsmgr
      - name: create users for developer job
        ansible.builtin.user:
          name: "{{ item.name }}"
          state: present
          groups: devops
          password: "{{ dev_pass | password_hash('sha512') }}"
        when: (inventory_hostname is in groups['dev'] or inventory_hostname is in groups['balancers']) and item.job == 'developer'
        loop: "{{ users }}"

      - name: create users for manager role
        ansible.builtin.user:
          name: "{{ item.name }}"
          state: present
          groups: opsmgr
          password: "{{ mgr_pass | password_hash('sha512') }}"
        when: inventory_hostname is in groups['prod'] and item.job == "manager"
        loop: "{{ users }}"

          
