---
  - name: generating file
    hosts: all
    tasks:
      - name: gemnerting file
        ansible.builtin.template:
          src: hosts.j2
          dest: /etc/hosts
        when: inventory_hostname is in groups['dev']
