---           
  - name: creating lvm
    hosts: all
    ignore_errors: true      
    tasks:           
      - name: verify vg exists 
        ansible.builtin.command:
          cmd: vgs research  
        register: vg 
                     
      - name: debug msg vg not found
        ansible.builtin.debug: 
          msg: "VG not found"
        when: vg.rc != 0
        
      - name: print
        debug:
          var: vg
